import { createContext, useContext, useState, ReactNode } from "react";

type Language = "en" | "ms";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    "nav.home": "Home",
    "nav.services": "Services",
    "nav.documents": "Required Documents",
    "nav.contact": "Contact",
    "nav.faq": "FAQ",
    "nav.about": "About",
    "nav.whatsapp": "WhatsApp",
    
    // Hero Section
    "hero.badge": "CNT Enterprise • Trusted Since 1984",
    "hero.title": "Cross-Border Vehicle Insurance",
    "hero.title.highlight": "for Malaysia–Thailand Travel",
    "hero.description": "Get the right insurance coverage before crossing the border. We handle the paperwork — you enjoy the journey. Staff-assisted processing with fast, reliable service.",
    "hero.cta.documents": "View Required Documents",
    "hero.cta.whatsapp": "Contact via WhatsApp",
    "hero.stats.policies": "Policies Processed",
    "hero.stats.years": "Years Experience",
    "hero.stats.satisfaction": "Satisfaction Rate",
    
    // How It Works
    "howitworks.badge": "How It Works",
    "howitworks.title": "Simple 4-Step Process",
    "howitworks.description": "Getting your Thailand vehicle insurance is easy. Our staff handles everything for you.",
    "howitworks.step1.title": "Prepare Required Documents",
    "howitworks.step1.description": "Gather your passport, vehicle registration (Grant), driving license, and other necessary documents.",
    "howitworks.step2.title": "Visit Office / Contact Staff",
    "howitworks.step2.description": "Visit our office in Changlun or contact our staff via WhatsApp for assistance with your application.",
    "howitworks.step3.title": "Insurance Processing & Verification",
    "howitworks.step3.description": "Our team processes your application and verifies all documents for Thai border compliance.",
    "howitworks.step4.title": "Policy Delivery",
    "howitworks.step4.description": "Receive your insurance policy via Email, Courier, or Counter pickup — whichever suits you best.",
    
    // Insurance Packages
    "packages.compulsory.title": "Compulsory Insurance Packages",
    "packages.compulsory.description": "Basic coverage for hospital bills if involved in an accident. Mandatory for entering Thailand.",
    "packages.voluntary.title": "Compulsory + Voluntary Packages",
    "packages.voluntary.description": "Additional coverage including third-party property/vehicle damage claims. Highly recommended to protect you from unexpected claims.",
    "packages.featured": "Featured",
    "packages.days": "Days",
    "packages.months": "Months",
    "packages.passengers": "passengers",
    "packages.from": "From",
    "packages.cta": "Contact Us for Details",
    "packages.interested": "Interested in getting coverage? Contact our staff for assistance.",
    
    // Why Choose Us
    "whychoose.badge": "Why Choose Us",
    "whychoose.title": "Why Choose ThaiDriveSecure",
    "whychoose.description": "We make cross-border insurance simple, reliable, and hassle-free.",
    "whychoose.fast.title": "Fast Processing",
    "whychoose.fast.description": "Quick turnaround on all insurance applications. Same-day processing available.",
    "whychoose.border.title": "Border-Ready Documentation",
    "whychoose.border.description": "All documents prepared and verified to meet Thai border authority requirements.",
    "whychoose.staff.title": "Staff-Assisted Verification",
    "whychoose.staff.description": "Our experienced team handles all paperwork and verification for you.",
    "whychoose.trusted.title": "Trusted & Reliable",
    "whychoose.trusted.description": "Over 40 years of experience helping Malaysian travellers cross safely.",
    "whychoose.delivery.title": "Flexible Delivery Options",
    "whychoose.delivery.description": "Choose from email, courier delivery, or counter pickup at your convenience.",
    "whychoose.support.title": "WhatsApp Support",
    "whychoose.support.description": "Quick responses and assistance via WhatsApp for all your queries.",
    
    // FAQ Section
    "faq.badge": "FAQ",
    "faq.title": "Frequently Asked Questions",
    "faq.description": "Get answers to the most common questions about cross-border vehicle insurance.",
    
    // Required Documents Page
    "documents.badge": "Document Checklist",
    "documents.title": "Documents Required to Enter Thailand by Vehicle",
    "documents.description": "Check off each document as you prepare. All items are required for border crossing.",
    "documents.vehicle": "Vehicle Documents",
    "documents.vehicle.roadtax": "Valid Malaysian Road Tax",
    "documents.vehicle.grant": "Vehicle Registration Grant (Geran Kenderaan)",
    "documents.vehicle.authorization": "Authorization Letter",
    "documents.personal": "Personal Identification",
    "documents.personal.passport": "Passport",
    "documents.personal.ic": "MyKad (IC) or Driving License",
    "documents.personal.photo": "Passport-size Photo",
    "documents.insurance": "Insurance Documents",
    "documents.insurance.tpbi": "Thailand TPBI Insurance Certificate",
    "documents.insurance.emergency": "Emergency Contact Card",
    "documents.insurance.hotline": "Insurance Hotline Number",
    "documents.required": "Required",
    "documents.help.title": "Need Help Preparing Your Documents?",
    "documents.help.description": "Our staff can assist you with document verification and insurance processing.",
    "documents.download": "Download PDF Checklist",
    
    // About Page
    "about.badge": "About Us",
    "about.title": "Your Trusted Partner for Cross-Border Insurance",
    "about.description": "Learn about CNT Enterprise and our mission to make Thailand travel safe and hassle-free.",
    "about.story.title": "Our Story",
    "about.story.p1": "CNT Enterprise was founded in 1984 with a simple mission: to help Malaysian travellers navigate the complexities of cross-border vehicle insurance with ease and confidence.",
    "about.story.p2": "Based in Changlun, Kedah — just minutes from the Thailand border — we understand the needs of travellers making the journey across. What started as a small family business has grown into a trusted name in cross-border insurance services.",
    "about.story.p3": "Over the years, we have helped more than 50,000 vehicles cross safely into Thailand, building a reputation for reliability, fast processing, and exceptional customer service.",
    "about.mission.title": "Our Mission",
    "about.mission.text": "To provide accessible, reliable, and hassle-free cross-border vehicle insurance services, ensuring every Malaysian traveller can enter Thailand with peace of mind and proper documentation.",
    "about.vision.title": "Our Vision",
    "about.vision.text": "To be the leading cross-border insurance facilitator in Malaysia, known for our commitment to customer service, transparency, and making international travel simple for everyone.",
    "about.values.title": "Our Values",
    "about.values.trust": "Trust & Reliability",
    "about.values.trust.desc": "We build lasting relationships through honest, dependable service.",
    "about.values.service": "Customer First",
    "about.values.service.desc": "Your needs and satisfaction are our top priority.",
    "about.values.simple": "Simplicity",
    "about.values.simple.desc": "We make complex processes easy to understand and complete.",
    "about.values.excellence": "Excellence",
    "about.values.excellence.desc": "We strive for the highest standards in everything we do.",
    "about.team.title": "Our Team",
    "about.team.description": "Our dedicated team of insurance professionals is here to assist you every step of the way.",
    "about.cta.title": "Ready to Get Started?",
    "about.cta.description": "Contact our team today to arrange your cross-border vehicle insurance.",
    
    // Contact Page
    "contact.badge": "Contact Us",
    "contact.title": "Get In Touch",
    "contact.description": "Have questions? Our staff is here to help with all your cross-border insurance needs.",
    "contact.info.title": "Contact Information",
    "contact.address": "Address",
    "contact.phone": "Phone",
    "contact.email": "Email",
    "contact.hours": "Operating Hours",
    "contact.note": "Note: All insurance applications are handled by our staff. Please contact us via WhatsApp or phone for assistance.",
    "contact.follow": "Follow Us",
    
    // Footer
    "footer.description": "Your trusted partner for cross-border vehicle insurance information and services.",
    "footer.quicklinks": "Quick Links",
    "footer.insurance": "Insurance Info",
    "footer.contact": "Contact Us",
    "footer.disclaimer": "Disclaimer: ThaiDriveSecure acts as a facilitation and service platform. All insurance applications are processed and handled by our staff. This website is for informational purposes only.",
    "footer.rights": "All rights reserved.",
    
    // Services
    "services.compulsory": "Compulsory Insurance (TPBI)",
    "services.compulsory.desc": "Mandatory coverage required by Thai law",
    "services.voluntary": "Voluntary Insurance",
    "services.voluntary.desc": "Extended protection beyond the minimum",
    "services.travel": "Travel & Personal Insurance",
    "services.travel.desc": "Personal accident and travel coverage",
    "services.addons": "Add-Ons & Extras",
    "services.addons.desc": "SIM cards, towing, roadside assistance",
    
    // Common
    "common.contactus": "Contact Us",
    "common.whatsappus": "WhatsApp Us",
    "common.learnmore": "Learn More",
    
    // App Download Section
    "app.badge": "Mobile App",
    "app.title": "Download Our Mobile App",
    "app.description": "Get insurance quotes, purchase coverage, and manage your policies directly from your smartphone. Download the ThaiDriveSecure app for a seamless experience.",
    "app.download": "Download APK",
    "app.android": "Available for Android devices",
    "app.tagline": "Your insurance companion",
    "app.new": "NEW!",
    "app.feature.instant": "Instant Quotes",
    "app.feature.instant.desc": "Get pricing in seconds",
    "app.feature.secure": "Secure Payment",
    "app.feature.secure.desc": "Safe transactions",
    "app.feature.manage": "Manage Policies",
    "app.feature.manage.desc": "View all your coverage",
    "app.mock.buy": "Buy Insurance",
    "app.mock.policies": "My Policies",
    "app.mock.documents": "Documents",
    "app.cta.title": "Get Insurance on the Go",
    "app.cta.description": "Download our mobile app to purchase insurance and manage your policies anytime, anywhere.",
    
    // Compulsory Insurance Page
    "compulsory.badge": "Insurance Info",
    "compulsory.title": "Compulsory Insurance (Por Ror Bor / TPBI)",
    "compulsory.description": "Understanding Thailand's mandatory Third Party Bodily Injury insurance requirement.",
    "compulsory.summary.title": "Coverage Summary",
    "compulsory.summary.text": "Compulsory Motor Insurance (Por Ror Bor) is mandatory by Thai law for all vehicles operating in Thailand. It provides basic coverage for third-party bodily injuries resulting from vehicle accidents. Without this insurance, you cannot legally drive in Thailand.",
    "compulsory.mandatory": "This insurance is MANDATORY for all vehicles entering Thailand",
    "compulsory.whatcovers": "What It Covers",
    "compulsory.whatnotcovers": "What It Does NOT Cover",
    "compulsory.coverage.1": "Medical expenses for third-party injuries",
    "compulsory.coverage.2": "Death benefits for third-party fatalities",
    "compulsory.coverage.3": "Hospital treatment costs",
    "compulsory.coverage.4": "Coverage up to 80,000 THB per person",
    "compulsory.coverage.5": "Coverage up to 5,000,000 THB per incident",
    "compulsory.notcovered.1": "Damage to your own vehicle",
    "compulsory.notcovered.2": "Damage to third-party property",
    "compulsory.notcovered.3": "Personal injury to the driver",
    "compulsory.notcovered.4": "Theft or fire damage",
    "compulsory.notcovered.5": "Natural disaster damage",
    "compulsory.whoneeds.title": "Who Needs This Insurance?",
    "compulsory.whoneeds.text": "All vehicle owners planning to drive in Thailand must have Compulsory Insurance. This includes Malaysian-registered cars, motorcycles, and trucks crossing the border. Thai authorities will check for valid insurance at border checkpoints. Driving without valid compulsory insurance is illegal and may result in fines or being denied entry.",
    "compulsory.when.title": "When Is It Required?",
    "compulsory.when.text": "Your insurance must be valid before you enter Thailand. Coverage should begin from your entry date and extend throughout your entire stay. We recommend arranging insurance at least 1-2 days before your planned departure to allow for processing time.",
    "compulsory.misunderstandings": "Common Misunderstandings",
    "compulsory.myth.1": "Malaysian insurance covers me in Thailand",
    "compulsory.fact.1": "Malaysian vehicle insurance does not provide coverage in Thailand. You need Thai-issued insurance.",
    "compulsory.myth.2": "Compulsory insurance covers all damage",
    "compulsory.fact.2": "Compulsory insurance only covers third-party bodily injuries, not property damage or your own vehicle.",
    "compulsory.myth.3": "I can buy insurance at the border",
    "compulsory.fact.3": "While possible at some checkpoints, it's better to arrange insurance in advance to avoid delays.",
    "compulsory.cta.title": "Need Compulsory Insurance?",
    "compulsory.cta.text": "Contact our staff to arrange your Thai compulsory insurance before your trip.",
    "compulsory.learnvoluntary": "Learn About Voluntary Insurance",
    
    // Voluntary Insurance Page
    "voluntary.badge": "Insurance Info",
    "voluntary.title": "Voluntary Insurance (Third Party Property)",
    "voluntary.description": "Extended protection beyond the mandatory minimum — highly recommended for complete peace of mind.",
    "voluntary.recommended": "Highly Recommended",
    "voluntary.recommended.text": "While not legally required, voluntary insurance is strongly recommended to protect yourself from potentially costly third-party property damage claims.",
    "voluntary.summary.title": "Coverage Summary",
    "voluntary.summary.text": "Voluntary Motor Insurance provides coverage beyond the mandatory TPBI. It covers third-party property damage including damage to other vehicles, buildings, and infrastructure. This is the insurance that protects you from large out-of-pocket expenses if you're at fault in an accident.",
    "voluntary.coverage.1": "Third-party property damage (vehicles, buildings, etc.)",
    "voluntary.coverage.2": "Higher limits for third-party bodily injury",
    "voluntary.coverage.3": "Legal liability coverage",
    "voluntary.coverage.4": "Property damage up to 1,000,000 THB",
    "voluntary.coverage.5": "Protection against \"duit pau\" (extortion claims)",
    "voluntary.whyrecommended": "Why Is It Recommended?",
    "voluntary.benefit.1.title": "Protection from large claims",
    "voluntary.benefit.1.desc": "Covers expensive third-party property damage claims that compulsory insurance doesn't cover.",
    "voluntary.benefit.2.title": "Peace of mind",
    "voluntary.benefit.2.desc": "Drive with confidence knowing you're protected against unexpected liability claims.",
    "voluntary.benefit.3.title": "Avoid \"duit pau\"",
    "voluntary.benefit.3.desc": "Some accident victims may demand unreasonable compensation. Voluntary insurance protects you.",
    "voluntary.benefit.4.title": "Higher coverage limits",
    "voluntary.benefit.4.desc": "Provides significantly higher coverage than the mandatory minimum.",
    "voluntary.whoneeds.title": "Who Needs This Insurance?",
    "voluntary.whoneeds.intro": "All drivers entering Thailand should consider voluntary insurance, especially if:",
    "voluntary.whoneeds.1": "You're driving on unfamiliar roads",
    "voluntary.whoneeds.2": "You're driving in busy urban areas like Hat Yai or Bangkok",
    "voluntary.whoneeds.3": "You want complete peace of mind during your trip",
    "voluntary.whoneeds.4": "You want to avoid potential disputes or \"duit pau\" situations",
    "voluntary.misunderstandings": "Common Misunderstandings",
    "voluntary.myth.1": "Compulsory insurance is enough",
    "voluntary.fact.1": "Compulsory only covers bodily injury. If you damage someone's expensive car, you pay out of pocket.",
    "voluntary.myth.2": "Voluntary insurance is very expensive",
    "voluntary.fact.2": "The additional cost is minimal compared to potential liability claims that could reach millions of baht.",
    "voluntary.myth.3": "I'm a careful driver, I don't need it",
    "voluntary.fact.3": "Accidents can happen to anyone. Voluntary insurance is protection against the unexpected.",
    "voluntary.when.title": "When Is It Required?",
    "voluntary.when.text": "Voluntary insurance is not legally required, but we strongly recommend purchasing it together with compulsory insurance. Both should be valid for the entire duration of your stay in Thailand. Our combined Compulsory + Voluntary packages offer the best value and complete protection.",
    "voluntary.cta.title": "Get Complete Protection",
    "voluntary.cta.text": "Contact our staff to get a combined Compulsory + Voluntary insurance package.",
    "voluntary.learntravel": "Learn About Travel Insurance",
    
    // Travel Insurance Page
    "travel.badge": "Insurance Info",
    "travel.title": "Travel & Personal Insurance",
    "travel.description": "Protect yourself and your passengers with comprehensive travel and personal accident coverage.",
    "travel.summary.title": "Coverage Summary",
    "travel.summary.text": "Travel and Personal Insurance provides protection for you and your passengers during your trip to Thailand. Unlike vehicle insurance which covers liability to third parties, this insurance covers your own medical expenses, personal accidents, and travel-related incidents.",
    "travel.coverage.1": "Personal accident coverage for driver and passengers",
    "travel.coverage.2": "Medical expenses while travelling",
    "travel.coverage.3": "Emergency medical evacuation",
    "travel.coverage.4": "Trip cancellation/interruption",
    "travel.coverage.5": "Lost or delayed baggage",
    "travel.coverage.6": "24/7 assistance hotline",
    "travel.benefits.title": "Key Benefits",
    "travel.benefit.1.title": "Medical emergencies abroad",
    "travel.benefit.1.desc": "Covers hospital bills, surgery, and medical treatment costs in Thailand.",
    "travel.benefit.2.title": "Personal accident protection",
    "travel.benefit.2.desc": "Compensation for injuries sustained during your trip, regardless of fault.",
    "travel.benefit.3.title": "Emergency evacuation",
    "travel.benefit.3.desc": "Covers costs of emergency medical transport if required.",
    "travel.benefit.4.title": "Peace of mind",
    "travel.benefit.4.desc": "Travel knowing you and your passengers are protected.",
    "travel.whoneeds.title": "Who Needs This Insurance?",
    "travel.whoneeds.intro": "Travel and personal insurance is recommended for:",
    "travel.whoneeds.1": "Drivers and all vehicle passengers",
    "travel.whoneeds.2": "Travelers with pre-existing medical conditions",
    "travel.whoneeds.3": "Those making extended trips to Thailand",
    "travel.whoneeds.4": "Anyone wanting complete protection beyond vehicle insurance",
    "travel.whoneeds.5": "Travelers without comprehensive international health coverage",
    "travel.misunderstandings": "Common Misunderstandings",
    "travel.myth.1": "Vehicle insurance covers personal injuries",
    "travel.fact.1": "Vehicle insurance covers third parties. You need personal/travel insurance for your own protection.",
    "travel.myth.2": "Malaysian health insurance works in Thailand",
    "travel.fact.2": "Most Malaysian health policies have limited overseas coverage. Travel insurance fills this gap.",
    "travel.myth.3": "I'm healthy, I don't need travel insurance",
    "travel.fact.3": "Accidents are unpredictable. Medical costs in Thailand can be expensive for foreigners.",
    "travel.when.title": "When Is It Required?",
    "travel.when.text": "Travel insurance is optional but highly recommended for all cross-border travellers. Coverage should begin from your departure date and extend until your return. Consider the duration of your trip and activities planned when choosing coverage levels.",
    "travel.cta.title": "Protect Your Journey",
    "travel.cta.text": "Contact our staff to learn about travel insurance options for your trip.",
    "travel.learnaddons": "View Add-Ons & Extras",
    
    // Add-Ons Page
    "addons.badge": "Extras",
    "addons.title": "Add-Ons & Extras",
    "addons.description": "Enhance your Thailand trip with convenient add-on services and extras.",
    "addons.popular": "Popular",
    "addons.sim.title": "Thailand SIM Card",
    "addons.sim.description": "Stay connected with a Thai mobile SIM card for data and calls during your trip.",
    "addons.sim.feature.1": "Data packages from 3GB to unlimited",
    "addons.sim.feature.2": "Valid for 7-30 days",
    "addons.sim.feature.3": "Covers major carriers (AIS, DTAC, TrueMove)",
    "addons.sim.feature.4": "Easy activation at the border or in advance",
    "addons.roadside.title": "Roadside Assistance",
    "addons.roadside.description": "24/7 emergency roadside assistance throughout Thailand.",
    "addons.roadside.feature.1": "Towing service (up to 50km)",
    "addons.roadside.feature.2": "Battery jump-start",
    "addons.roadside.feature.3": "Flat tire assistance",
    "addons.roadside.feature.4": "Fuel delivery",
    "addons.roadside.feature.5": "Lockout service",
    "addons.gps.title": "GPS Navigation",
    "addons.gps.description": "Portable GPS device rental with Thailand maps pre-loaded.",
    "addons.gps.feature.1": "Full Thailand map coverage",
    "addons.gps.feature.2": "Turn-by-turn navigation",
    "addons.gps.feature.3": "Points of interest included",
    "addons.gps.feature.4": "Multi-language support",
    "addons.emergency.title": "Emergency Hotline Card",
    "addons.emergency.description": "Quick reference card with all emergency numbers and assistance contacts.",
    "addons.emergency.feature.1": "Thai emergency numbers (police, ambulance, fire)",
    "addons.emergency.feature.2": "Our 24/7 support hotline",
    "addons.emergency.feature.3": "Embassy contact numbers",
    "addons.emergency.feature.4": "Insurance claim instructions",
    "addons.whoneeds.title": "Who Needs These Services?",
    "addons.whoneeds.intro": "Add-on services are recommended for:",
    "addons.whoneeds.1": "First-time visitors to Thailand",
    "addons.whoneeds.2": "Those making long road trips beyond border towns",
    "addons.whoneeds.3": "Travelers who want to stay connected with family",
    "addons.whoneeds.4": "Drivers who want peace of mind with 24/7 roadside support",
    "addons.misunderstandings": "Common Misunderstandings",
    "addons.myth.1": "My Malaysian phone will work fine in Thailand",
    "addons.fact.1": "While roaming works, data costs are expensive. A Thai SIM provides much better value.",
    "addons.myth.2": "I can just use Google Maps offline",
    "addons.fact.2": "Offline maps don't show traffic or provide real-time rerouting. Consider GPS for longer trips.",
    "addons.myth.3": "Roadside assistance is only for old cars",
    "addons.fact.3": "Flat tires, dead batteries, and lockouts can happen to any vehicle regardless of age.",
    "addons.availability.title": "Availability",
    "addons.availability.text": "Add-on services are subject to availability and may vary. Contact our staff for current offerings and pricing. Some services may require advance booking. All add-ons can be arranged together with your insurance application.",
    "addons.cta.title": "Interested in Add-Ons?",
    "addons.cta.text": "Contact our staff to learn about available extras for your trip.",
    "addons.viewdocuments": "View Required Documents",
    
    // Insurance Comparison Section
    "compare.badge": "Compare Coverage",
    "compare.title": "Compulsory vs Voluntary Insurance",
    "compare.description": "Understand the key differences between compulsory and voluntary coverage to make an informed decision.",
    "compare.feature": "Coverage Feature",
    "compare.compulsory": "Compulsory",
    "compare.compulsory.sub": "Por Ror Bor / TPBI",
    "compare.voluntary": "Compulsory + Voluntary",
    "compare.voluntary.sub": "Complete Protection",
    "compare.recommended": "Recommended",
    "compare.feature.legal": "Legally required to enter Thailand",
    "compare.feature.thirdparty": "Third-party bodily injury",
    "compare.feature.property": "Third-party property damage",
    "compare.feature.ownvehicle": "Own vehicle damage",
    "compare.feature.highermedical": "Higher medical coverage limits",
    "compare.feature.duitpau": "Protection from \"duit pau\" claims",
    "compare.feature.legal.liability": "Legal liability coverage",
    "compare.note.comprehensive": "Requires comprehensive insurance",
    "compare.compulsory.summary": "Basic mandatory coverage for bodily injury only. Required by law but limited protection.",
    "compare.voluntary.summary": "Complete protection including property damage. Highly recommended for peace of mind.",
    
    // Border Guide Page
    "nav.borderguide": "Border Guide",
    "border.badge": "Step-by-Step Guide",
    "border.title": "Thailand Border Crossing Guide",
    "border.description": "Know exactly what to expect at the border checkpoint. Follow this visual guide for a smooth crossing experience.",
    "border.overview.title": "What to Expect",
    "border.overview.text": "Crossing the Malaysia-Thailand border by vehicle typically takes 30 minutes to 2 hours depending on traffic. The process involves Malaysian exit immigration, Thai entry immigration, vehicle customs, and insurance verification. Being prepared with all documents will make the process much faster.",
    "border.step1.title": "Malaysian Exit Immigration",
    "border.step1.description": "First, you will pass through Malaysian immigration at the departure hall. Present your passport for an exit stamp. All passengers must disembark and go through the checkpoint.",
    "border.step1.tip1": "Have all passports ready and accessible",
    "border.step1.tip2": "Remove hats and sunglasses for photo verification",
    "border.step1.tip3": "Keep vehicle documents handy for quick reference",
    "border.step2.title": "Insurance Verification",
    "border.step2.description": "Before proceeding to Thai immigration, you need valid Thai vehicle insurance. If you arranged insurance with us beforehand, have your policy documents ready for inspection.",
    "border.step2.tip1": "Ensure insurance covers your entire trip duration",
    "border.step2.tip2": "Keep both physical and digital copies of your policy",
    "border.step2.tip3": "Verify the vehicle registration matches your insurance",
    "border.step3.title": "Vehicle Customs Inspection",
    "border.step3.description": "Your vehicle will undergo customs inspection. Officers may check your boot and interior. Prohibited items include certain foods, weapons, and controlled substances.",
    "border.step3.tip1": "Declare any items if unsure about regulations",
    "border.step3.tip2": "Keep your vehicle clean and organized",
    "border.step3.tip3": "Have vehicle registration (Grant) ready to show",
    "border.step4.title": "Thai Entry Immigration",
    "border.step4.description": "Present your passport at Thai immigration for an entry stamp. You may need to fill out an arrival/departure card. Malaysians typically get 30 days visa-free entry.",
    "border.step4.tip1": "Fill out the TM6 arrival card if required",
    "border.step4.tip2": "Keep the departure card safe - you need it when leaving",
    "border.step4.tip3": "Know your intended address in Thailand",
    "border.step5.title": "Enter Thailand",
    "border.step5.description": "Once cleared, you can drive into Thailand. Remember to drive on the left side (same as Malaysia). Follow local traffic rules and speed limits.",
    "border.step5.tip1": "Switch to Thai time zone (same as Malaysia)",
    "border.step5.tip2": "Have Thai Baht ready for tolls and expenses",
    "border.step5.tip3": "Download offline maps for your destination",
    "border.tips.label": "Tips",
    "border.essential.title": "Essential Tips for Border Crossing",
    "border.tips.timing.title": "Best Crossing Times",
    "border.tips.timing.desc": "Weekday mornings (7-9 AM) are usually less crowded. Avoid public holidays and long weekends.",
    "border.tips.photos.title": "Take Photos",
    "border.tips.photos.desc": "Photograph your documents, insurance policy, and vehicle mileage before crossing for your records.",
    "border.tips.money.title": "Currency & Payment",
    "border.tips.money.desc": "Bring Thai Baht for expenses. ATMs are available on the Thai side. Most places accept cash only.",
    "border.tips.language.title": "Language Help",
    "border.tips.language.desc": "Basic Thai phrases help. Border officers usually speak some English. Translation apps are useful.",
    "border.warning.title": "Important Reminder",
    "border.warning.text": "Border procedures may vary and are subject to change. This guide is for general reference only. Always follow instructions from immigration and customs officers. Requirements may differ based on current regulations, time of day, or checkpoint location.",
    "border.cta.title": "Ready to Cross the Border?",
    "border.cta.text": "Make sure you have all required documents and valid insurance before your trip.",
    "border.cta.documents": "View Required Documents",
    
    // Border Locations
    "border.locations.title": "Border Crossing Locations",
    "border.location.icqs": "Immigration, Customs, Quarantine & Security",
    "border.location.bkh.title": "Bukit Kayu Hitam Border Location",
    "border.location.bkh.short": "Bukit Kayu Hitam",
    "border.location.bkh.name": "Bukit Kayu Hitam ICQS Complex",
    "border.location.bkh.context": "The busiest and most popular border crossing between Malaysia and Thailand. Located in Kedah, it provides direct access to Sadao, Thailand and is ideal for travelers heading to Hat Yai and beyond.",
    "border.location.pb.title": "Padang Besar Border Location",
    "border.location.pb.short": "Padang Besar",
    "border.location.pb.name": "Padang Besar ICQS Complex",
    "border.location.pb.context": "A major border crossing frequently used by travelers heading to Hat Yai, with direct access to the Thailand railway network.",
    "border.location.wk.title": "Wang Kelian Border Location",
    "border.location.wk.short": "Wang Kelian",
    "border.location.wk.name": "Wang Kelian ICQS Complex",
    "border.location.wk.context": "Previously popular due to a border market. Although less active today, it remains an accessible crossing option.",
    "border.location.db.title": "Durian Burung Border Location",
    "border.location.db.short": "Durian Burung",
    "border.location.db.name": "Durian Burung ICQS Complex",
    "border.location.db.context": "The newest and quietest border crossing. Its remote location results in lower traffic, suitable for travelers seeking less congestion.",
  },
  ms: {
    // Navigation
    "nav.home": "Utama",
    "nav.services": "Perkhidmatan",
    "nav.documents": "Dokumen Diperlukan",
    "nav.contact": "Hubungi",
    "nav.faq": "Soalan Lazim",
    "nav.about": "Tentang Kami",
    "nav.whatsapp": "WhatsApp",
    
    // Hero Section
    "hero.badge": "CNT Enterprise • Dipercayai Sejak 1984",
    "hero.title": "Insurans Kenderaan Rentas Sempadan",
    "hero.title.highlight": "untuk Perjalanan Malaysia–Thailand",
    "hero.description": "Dapatkan perlindungan insurans yang betul sebelum merentasi sempadan. Kami uruskan dokumen — anda nikmati perjalanan. Pemprosesan dibantu kakitangan dengan perkhidmatan pantas dan boleh dipercayai.",
    "hero.cta.documents": "Lihat Dokumen Diperlukan",
    "hero.cta.whatsapp": "Hubungi via WhatsApp",
    "hero.stats.policies": "Polisi Diproses",
    "hero.stats.years": "Tahun Pengalaman",
    "hero.stats.satisfaction": "Kadar Kepuasan",
    
    // How It Works
    "howitworks.badge": "Cara Ia Berfungsi",
    "howitworks.title": "Proses 4 Langkah Mudah",
    "howitworks.description": "Mendapatkan insurans kenderaan Thailand anda mudah. Kakitangan kami menguruskan semuanya untuk anda.",
    "howitworks.step1.title": "Sediakan Dokumen Diperlukan",
    "howitworks.step1.description": "Kumpulkan pasport, pendaftaran kenderaan (Geran), lesen memandu, dan dokumen lain yang diperlukan.",
    "howitworks.step2.title": "Lawat Pejabat / Hubungi Kakitangan",
    "howitworks.step2.description": "Lawat pejabat kami di Changlun atau hubungi kakitangan kami melalui WhatsApp untuk bantuan permohonan anda.",
    "howitworks.step3.title": "Pemprosesan & Pengesahan Insurans",
    "howitworks.step3.description": "Pasukan kami memproses permohonan anda dan mengesahkan semua dokumen untuk pematuhan sempadan Thai.",
    "howitworks.step4.title": "Penghantaran Polisi",
    "howitworks.step4.description": "Terima polisi insurans anda melalui E-mel, Kurier, atau Pengambilan di Kaunter — mengikut keselesaan anda.",
    
    // Insurance Packages
    "packages.compulsory.title": "Pakej Insurans Wajib",
    "packages.compulsory.description": "Perlindungan asas bil rawatan hospital sekiranya terlibat dalam kemalangan. Wajib dibeli untuk ke Thailand.",
    "packages.voluntary.title": "Pakej Wajib + Sukarela",
    "packages.voluntary.description": "Perlindungan tambahan meliputi tuntutan kerosakan harta/kenderaan pihak ketiga. Amat digalakkan untuk melindungi anda dari tuntutan luar jangka.",
    "packages.featured": "Pilihan",
    "packages.days": "Hari",
    "packages.months": "Bulan",
    "packages.passengers": "penumpang",
    "packages.from": "Dari",
    "packages.cta": "Hubungi Kami untuk Maklumat",
    "packages.interested": "Berminat untuk mendapatkan perlindungan? Hubungi kakitangan kami untuk bantuan.",
    
    // Why Choose Us
    "whychoose.badge": "Mengapa Pilih Kami",
    "whychoose.title": "Mengapa Pilih ThaiDriveSecure",
    "whychoose.description": "Kami menjadikan insurans rentas sempadan mudah, boleh dipercayai, dan tanpa kerumitan.",
    "whychoose.fast.title": "Pemprosesan Pantas",
    "whychoose.fast.description": "Pemprosesan cepat untuk semua permohonan insurans. Pemprosesan hari yang sama tersedia.",
    "whychoose.border.title": "Dokumentasi Sedia Sempadan",
    "whychoose.border.description": "Semua dokumen disediakan dan disahkan untuk memenuhi keperluan pihak berkuasa sempadan Thai.",
    "whychoose.staff.title": "Pengesahan Dibantu Kakitangan",
    "whychoose.staff.description": "Pasukan berpengalaman kami menguruskan semua kerja dokumentasi dan pengesahan untuk anda.",
    "whychoose.trusted.title": "Dipercayai & Boleh Dipercayai",
    "whychoose.trusted.description": "Lebih 40 tahun pengalaman membantu pelancong Malaysia merentasi dengan selamat.",
    "whychoose.delivery.title": "Pilihan Penghantaran Fleksibel",
    "whychoose.delivery.description": "Pilih daripada e-mel, penghantaran kurier, atau pengambilan di kaunter mengikut keselesaan anda.",
    "whychoose.support.title": "Sokongan WhatsApp",
    "whychoose.support.description": "Respons pantas dan bantuan melalui WhatsApp untuk semua pertanyaan anda.",
    
    // FAQ Section
    "faq.badge": "Soalan Lazim",
    "faq.title": "Soalan Yang Sering Ditanya",
    "faq.description": "Dapatkan jawapan kepada soalan paling biasa tentang insurans kenderaan rentas sempadan.",
    
    // Required Documents Page
    "documents.badge": "Senarai Semak Dokumen",
    "documents.title": "Dokumen Diperlukan untuk Memasuki Thailand dengan Kenderaan",
    "documents.description": "Tandakan setiap dokumen semasa anda menyediakannya. Semua item diperlukan untuk rentas sempadan.",
    "documents.vehicle": "Dokumen Kenderaan",
    "documents.vehicle.roadtax": "Cukai Jalan Malaysia yang Sah",
    "documents.vehicle.grant": "Geran Pendaftaran Kenderaan",
    "documents.vehicle.authorization": "Surat Kebenaran",
    "documents.personal": "Pengenalan Peribadi",
    "documents.personal.passport": "Pasport",
    "documents.personal.ic": "MyKad (IC) atau Lesen Memandu",
    "documents.personal.photo": "Foto Saiz Pasport",
    "documents.insurance": "Dokumen Insurans",
    "documents.insurance.tpbi": "Sijil Insurans TPBI Thailand",
    "documents.insurance.emergency": "Kad Kenalan Kecemasan",
    "documents.insurance.hotline": "Nombor Talian Insurans",
    "documents.required": "Diperlukan",
    "documents.help.title": "Perlukan Bantuan Menyediakan Dokumen Anda?",
    "documents.help.description": "Kakitangan kami boleh membantu anda dengan pengesahan dokumen dan pemprosesan insurans.",
    "documents.download": "Muat Turun Senarai Semak PDF",
    
    // About Page
    "about.badge": "Tentang Kami",
    "about.title": "Rakan Dipercayai Anda untuk Insurans Rentas Sempadan",
    "about.description": "Ketahui tentang CNT Enterprise dan misi kami untuk menjadikan perjalanan ke Thailand selamat dan tanpa kerumitan.",
    "about.story.title": "Kisah Kami",
    "about.story.p1": "CNT Enterprise ditubuhkan pada 1984 dengan misi mudah: untuk membantu pelancong Malaysia mengemudi kerumitan insurans kenderaan rentas sempadan dengan mudah dan yakin.",
    "about.story.p2": "Berpusat di Changlun, Kedah — hanya beberapa minit dari sempadan Thailand — kami memahami keperluan pelancong yang membuat perjalanan merentasi. Apa yang bermula sebagai perniagaan keluarga kecil telah berkembang menjadi nama yang dipercayai dalam perkhidmatan insurans rentas sempadan.",
    "about.story.p3": "Selama bertahun-tahun, kami telah membantu lebih daripada 50,000 kenderaan merentasi dengan selamat ke Thailand, membina reputasi untuk kebolehpercayaan, pemprosesan pantas, dan perkhidmatan pelanggan yang luar biasa.",
    "about.mission.title": "Misi Kami",
    "about.mission.text": "Untuk menyediakan perkhidmatan insurans kenderaan rentas sempadan yang mudah diakses, boleh dipercayai, dan tanpa kerumitan, memastikan setiap pelancong Malaysia dapat memasuki Thailand dengan ketenangan fikiran dan dokumentasi yang betul.",
    "about.vision.title": "Visi Kami",
    "about.vision.text": "Untuk menjadi fasilitator insurans rentas sempadan terkemuka di Malaysia, dikenali dengan komitmen kami terhadap perkhidmatan pelanggan, ketelusan, dan menjadikan perjalanan antarabangsa mudah untuk semua orang.",
    "about.values.title": "Nilai-Nilai Kami",
    "about.values.trust": "Kepercayaan & Kebolehpercayaan",
    "about.values.trust.desc": "Kami membina hubungan berkekalan melalui perkhidmatan yang jujur dan boleh diharap.",
    "about.values.service": "Pelanggan Diutamakan",
    "about.values.service.desc": "Keperluan dan kepuasan anda adalah keutamaan kami.",
    "about.values.simple": "Kesederhanaan",
    "about.values.simple.desc": "Kami menjadikan proses yang kompleks mudah difahami dan diselesaikan.",
    "about.values.excellence": "Kecemerlangan",
    "about.values.excellence.desc": "Kami berusaha untuk standard tertinggi dalam segala yang kami lakukan.",
    "about.team.title": "Pasukan Kami",
    "about.team.description": "Pasukan profesional insurans kami yang berdedikasi sedia membantu anda setiap langkah.",
    "about.cta.title": "Bersedia untuk Bermula?",
    "about.cta.description": "Hubungi pasukan kami hari ini untuk mengatur insurans kenderaan rentas sempadan anda.",
    
    // Contact Page
    "contact.badge": "Hubungi Kami",
    "contact.title": "Berhubung dengan Kami",
    "contact.description": "Ada soalan? Kakitangan kami sedia membantu dengan semua keperluan insurans rentas sempadan anda.",
    "contact.info.title": "Maklumat Hubungan",
    "contact.address": "Alamat",
    "contact.phone": "Telefon",
    "contact.email": "E-mel",
    "contact.hours": "Waktu Operasi",
    "contact.note": "Nota: Semua permohonan insurans diuruskan oleh kakitangan kami. Sila hubungi kami melalui WhatsApp atau telefon untuk bantuan.",
    "contact.follow": "Ikuti Kami",
    
    // Footer
    "footer.description": "Rakan dipercayai anda untuk maklumat dan perkhidmatan insurans kenderaan rentas sempadan.",
    "footer.quicklinks": "Pautan Pantas",
    "footer.insurance": "Info Insurans",
    "footer.contact": "Hubungi Kami",
    "footer.disclaimer": "Penafian: ThaiDriveSecure bertindak sebagai platform fasilitasi dan perkhidmatan. Semua permohonan insurans diproses dan diuruskan oleh kakitangan kami. Laman web ini adalah untuk tujuan maklumat sahaja.",
    "footer.rights": "Hak cipta terpelihara.",
    
    // Services
    "services.compulsory": "Insurans Wajib (TPBI)",
    "services.compulsory.desc": "Perlindungan wajib yang diperlukan oleh undang-undang Thai",
    "services.voluntary": "Insurans Sukarela",
    "services.voluntary.desc": "Perlindungan lanjutan melebihi minimum",
    "services.travel": "Insurans Perjalanan & Peribadi",
    "services.travel.desc": "Perlindungan kemalangan peribadi dan perjalanan",
    "services.addons": "Tambahan & Ekstra",
    "services.addons.desc": "Kad SIM, tunda, bantuan jalan raya",
    
    // Common
    "common.contactus": "Hubungi Kami",
    "common.whatsappus": "WhatsApp Kami",
    "common.learnmore": "Ketahui Lebih Lanjut",
    
    // App Download Section
    "app.badge": "Aplikasi Mudah Alih",
    "app.title": "Muat Turun Aplikasi Mudah Alih Kami",
    "app.description": "Dapatkan sebut harga insurans, beli perlindungan, dan uruskan polisi anda terus dari telefon pintar. Muat turun aplikasi ThaiDriveSecure untuk pengalaman yang lancar.",
    "app.download": "Muat Turun APK",
    "app.android": "Tersedia untuk peranti Android",
    "app.tagline": "Teman insurans anda",
    "app.new": "BARU!",
    "app.feature.instant": "Sebut Harga Segera",
    "app.feature.instant.desc": "Dapatkan harga dalam saat",
    "app.feature.secure": "Pembayaran Selamat",
    "app.feature.secure.desc": "Transaksi yang selamat",
    "app.feature.manage": "Urus Polisi",
    "app.feature.manage.desc": "Lihat semua perlindungan anda",
    "app.mock.buy": "Beli Insurans",
    "app.mock.policies": "Polisi Saya",
    "app.mock.documents": "Dokumen",
    "app.cta.title": "Dapatkan Insurans Dalam Perjalanan",
    "app.cta.description": "Muat turun aplikasi mudah alih kami untuk membeli insurans dan menguruskan polisi anda bila-bila masa, di mana sahaja.",
    
    // Compulsory Insurance Page
    "compulsory.badge": "Info Insurans",
    "compulsory.title": "Insurans Wajib (Por Ror Bor / TPBI)",
    "compulsory.description": "Memahami keperluan insurans Kecederaan Badan Pihak Ketiga wajib Thailand.",
    "compulsory.summary.title": "Ringkasan Perlindungan",
    "compulsory.summary.text": "Insurans Motor Wajib (Por Ror Bor) diwajibkan oleh undang-undang Thai untuk semua kenderaan yang beroperasi di Thailand. Ia menyediakan perlindungan asas untuk kecederaan badan pihak ketiga akibat kemalangan kenderaan. Tanpa insurans ini, anda tidak boleh memandu secara sah di Thailand.",
    "compulsory.mandatory": "Insurans ini WAJIB untuk semua kenderaan yang memasuki Thailand",
    "compulsory.whatcovers": "Apa Yang Dilindungi",
    "compulsory.whatnotcovers": "Apa Yang TIDAK Dilindungi",
    "compulsory.coverage.1": "Perbelanjaan perubatan untuk kecederaan pihak ketiga",
    "compulsory.coverage.2": "Manfaat kematian untuk kematian pihak ketiga",
    "compulsory.coverage.3": "Kos rawatan hospital",
    "compulsory.coverage.4": "Perlindungan sehingga 80,000 THB setiap orang",
    "compulsory.coverage.5": "Perlindungan sehingga 5,000,000 THB setiap insiden",
    "compulsory.notcovered.1": "Kerosakan kenderaan anda sendiri",
    "compulsory.notcovered.2": "Kerosakan harta pihak ketiga",
    "compulsory.notcovered.3": "Kecederaan peribadi kepada pemandu",
    "compulsory.notcovered.4": "Kecurian atau kerosakan akibat kebakaran",
    "compulsory.notcovered.5": "Kerosakan akibat bencana alam",
    "compulsory.whoneeds.title": "Siapa Yang Memerlukan Insurans Ini?",
    "compulsory.whoneeds.text": "Semua pemilik kenderaan yang bercadang untuk memandu di Thailand mesti mempunyai Insurans Wajib. Ini termasuk kereta, motosikal, dan trak berdaftar Malaysia yang merentasi sempadan. Pihak berkuasa Thai akan memeriksa insurans yang sah di pusat pemeriksaan sempadan. Memandu tanpa insurans wajib yang sah adalah menyalahi undang-undang dan boleh mengakibatkan denda atau dinafikan kemasukan.",
    "compulsory.when.title": "Bila Ia Diperlukan?",
    "compulsory.when.text": "Insurans anda mesti sah sebelum anda memasuki Thailand. Perlindungan harus bermula dari tarikh kemasukan anda dan meliputi sepanjang penginapan anda. Kami mengesyorkan untuk mengatur insurans sekurang-kurangnya 1-2 hari sebelum perlepasan yang dirancang untuk membenarkan masa pemprosesan.",
    "compulsory.misunderstandings": "Salah Faham Biasa",
    "compulsory.myth.1": "Insurans Malaysia melindungi saya di Thailand",
    "compulsory.fact.1": "Insurans kenderaan Malaysia tidak menyediakan perlindungan di Thailand. Anda memerlukan insurans yang dikeluarkan Thai.",
    "compulsory.myth.2": "Insurans wajib melindungi semua kerosakan",
    "compulsory.fact.2": "Insurans wajib hanya melindungi kecederaan badan pihak ketiga, bukan kerosakan harta atau kenderaan anda sendiri.",
    "compulsory.myth.3": "Saya boleh beli insurans di sempadan",
    "compulsory.fact.3": "Walaupun mungkin di sesetengah pusat pemeriksaan, lebih baik mengatur insurans terlebih dahulu untuk mengelakkan kelewatan.",
    "compulsory.cta.title": "Perlukan Insurans Wajib?",
    "compulsory.cta.text": "Hubungi kakitangan kami untuk mengatur insurans wajib Thai anda sebelum perjalanan.",
    "compulsory.learnvoluntary": "Ketahui Tentang Insurans Sukarela",
    
    // Voluntary Insurance Page
    "voluntary.badge": "Info Insurans",
    "voluntary.title": "Insurans Sukarela (Harta Pihak Ketiga)",
    "voluntary.description": "Perlindungan lanjutan melebihi minimum mandatori — sangat disyorkan untuk ketenangan fikiran sepenuhnya.",
    "voluntary.recommended": "Sangat Disyorkan",
    "voluntary.recommended.text": "Walaupun tidak diwajibkan secara undang-undang, insurans sukarela sangat disyorkan untuk melindungi diri anda daripada tuntutan kerosakan harta pihak ketiga yang berpotensi mahal.",
    "voluntary.summary.title": "Ringkasan Perlindungan",
    "voluntary.summary.text": "Insurans Motor Sukarela menyediakan perlindungan melebihi TPBI mandatori. Ia melindungi kerosakan harta pihak ketiga termasuk kerosakan kepada kenderaan lain, bangunan, dan infrastruktur. Ini adalah insurans yang melindungi anda daripada perbelanjaan besar dari poket sendiri jika anda bersalah dalam kemalangan.",
    "voluntary.coverage.1": "Kerosakan harta pihak ketiga (kenderaan, bangunan, dll.)",
    "voluntary.coverage.2": "Had lebih tinggi untuk kecederaan badan pihak ketiga",
    "voluntary.coverage.3": "Perlindungan liabiliti undang-undang",
    "voluntary.coverage.4": "Kerosakan harta sehingga 1,000,000 THB",
    "voluntary.coverage.5": "Perlindungan terhadap \"duit pau\" (tuntutan peras ugut)",
    "voluntary.whyrecommended": "Mengapa Ia Disyorkan?",
    "voluntary.benefit.1.title": "Perlindungan dari tuntutan besar",
    "voluntary.benefit.1.desc": "Melindungi tuntutan kerosakan harta pihak ketiga yang mahal yang tidak dilindungi oleh insurans wajib.",
    "voluntary.benefit.2.title": "Ketenangan fikiran",
    "voluntary.benefit.2.desc": "Memandu dengan yakin mengetahui anda dilindungi terhadap tuntutan liabiliti yang tidak dijangka.",
    "voluntary.benefit.3.title": "Elakkan \"duit pau\"",
    "voluntary.benefit.3.desc": "Sesetengah mangsa kemalangan mungkin menuntut pampasan yang tidak munasabah. Insurans sukarela melindungi anda.",
    "voluntary.benefit.4.title": "Had perlindungan lebih tinggi",
    "voluntary.benefit.4.desc": "Menyediakan perlindungan yang jauh lebih tinggi daripada minimum mandatori.",
    "voluntary.whoneeds.title": "Siapa Yang Memerlukan Insurans Ini?",
    "voluntary.whoneeds.intro": "Semua pemandu yang memasuki Thailand harus mempertimbangkan insurans sukarela, terutamanya jika:",
    "voluntary.whoneeds.1": "Anda memandu di jalan yang tidak biasa",
    "voluntary.whoneeds.2": "Anda memandu di kawasan bandar yang sibuk seperti Hat Yai atau Bangkok",
    "voluntary.whoneeds.3": "Anda mahukan ketenangan fikiran sepenuhnya semasa perjalanan",
    "voluntary.whoneeds.4": "Anda mahu mengelakkan potensi pertikaian atau situasi \"duit pau\"",
    "voluntary.misunderstandings": "Salah Faham Biasa",
    "voluntary.myth.1": "Insurans wajib sudah cukup",
    "voluntary.fact.1": "Wajib hanya melindungi kecederaan badan. Jika anda merosakkan kereta mahal seseorang, anda bayar dari poket sendiri.",
    "voluntary.myth.2": "Insurans sukarela sangat mahal",
    "voluntary.fact.2": "Kos tambahan adalah minimum berbanding potensi tuntutan liabiliti yang boleh mencecah jutaan baht.",
    "voluntary.myth.3": "Saya pemandu berhati-hati, saya tidak memerlukannya",
    "voluntary.fact.3": "Kemalangan boleh berlaku kepada sesiapa sahaja. Insurans sukarela adalah perlindungan terhadap yang tidak dijangka.",
    "voluntary.when.title": "Bila Ia Diperlukan?",
    "voluntary.when.text": "Insurans sukarela tidak diwajibkan secara undang-undang, tetapi kami sangat mengesyorkan membelinya bersama insurans wajib. Kedua-duanya harus sah untuk keseluruhan tempoh penginapan anda di Thailand. Pakej gabungan Wajib + Sukarela kami menawarkan nilai terbaik dan perlindungan lengkap.",
    "voluntary.cta.title": "Dapatkan Perlindungan Lengkap",
    "voluntary.cta.text": "Hubungi kakitangan kami untuk mendapatkan pakej insurans gabungan Wajib + Sukarela.",
    "voluntary.learntravel": "Ketahui Tentang Insurans Perjalanan",
    
    // Travel Insurance Page
    "travel.badge": "Info Insurans",
    "travel.title": "Insurans Perjalanan & Peribadi",
    "travel.description": "Lindungi diri anda dan penumpang anda dengan perlindungan perjalanan dan kemalangan peribadi yang komprehensif.",
    "travel.summary.title": "Ringkasan Perlindungan",
    "travel.summary.text": "Insurans Perjalanan dan Peribadi menyediakan perlindungan untuk anda dan penumpang anda semasa perjalanan ke Thailand. Tidak seperti insurans kenderaan yang melindungi liabiliti kepada pihak ketiga, insurans ini melindungi perbelanjaan perubatan anda sendiri, kemalangan peribadi, dan insiden berkaitan perjalanan.",
    "travel.coverage.1": "Perlindungan kemalangan peribadi untuk pemandu dan penumpang",
    "travel.coverage.2": "Perbelanjaan perubatan semasa dalam perjalanan",
    "travel.coverage.3": "Pemindahan perubatan kecemasan",
    "travel.coverage.4": "Pembatalan/gangguan perjalanan",
    "travel.coverage.5": "Bagasi hilang atau tertunda",
    "travel.coverage.6": "Talian bantuan 24/7",
    "travel.benefits.title": "Faedah Utama",
    "travel.benefit.1.title": "Kecemasan perubatan di luar negara",
    "travel.benefit.1.desc": "Melindungi bil hospital, pembedahan, dan kos rawatan perubatan di Thailand.",
    "travel.benefit.2.title": "Perlindungan kemalangan peribadi",
    "travel.benefit.2.desc": "Pampasan untuk kecederaan yang dialami semasa perjalanan anda, tanpa mengira kesalahan.",
    "travel.benefit.3.title": "Pemindahan kecemasan",
    "travel.benefit.3.desc": "Melindungi kos pengangkutan perubatan kecemasan jika diperlukan.",
    "travel.benefit.4.title": "Ketenangan fikiran",
    "travel.benefit.4.desc": "Perjalanan dengan mengetahui anda dan penumpang anda dilindungi.",
    "travel.whoneeds.title": "Siapa Yang Memerlukan Insurans Ini?",
    "travel.whoneeds.intro": "Insurans perjalanan dan peribadi disyorkan untuk:",
    "travel.whoneeds.1": "Pemandu dan semua penumpang kenderaan",
    "travel.whoneeds.2": "Pelancong dengan keadaan perubatan sedia ada",
    "travel.whoneeds.3": "Mereka yang membuat perjalanan panjang ke Thailand",
    "travel.whoneeds.4": "Sesiapa yang mahukan perlindungan lengkap melebihi insurans kenderaan",
    "travel.whoneeds.5": "Pelancong tanpa perlindungan kesihatan antarabangsa yang komprehensif",
    "travel.misunderstandings": "Salah Faham Biasa",
    "travel.myth.1": "Insurans kenderaan melindungi kecederaan peribadi",
    "travel.fact.1": "Insurans kenderaan melindungi pihak ketiga. Anda memerlukan insurans peribadi/perjalanan untuk perlindungan anda sendiri.",
    "travel.myth.2": "Insurans kesihatan Malaysia berfungsi di Thailand",
    "travel.fact.2": "Kebanyakan polisi kesihatan Malaysia mempunyai perlindungan luar negara yang terhad. Insurans perjalanan mengisi jurang ini.",
    "travel.myth.3": "Saya sihat, saya tidak memerlukan insurans perjalanan",
    "travel.fact.3": "Kemalangan tidak dapat diramalkan. Kos perubatan di Thailand boleh mahal untuk warga asing.",
    "travel.when.title": "Bila Ia Diperlukan?",
    "travel.when.text": "Insurans perjalanan adalah pilihan tetapi sangat disyorkan untuk semua pelancong rentas sempadan. Perlindungan harus bermula dari tarikh perlepasan anda dan meliputi sehingga kepulangan anda. Pertimbangkan tempoh perjalanan dan aktiviti yang dirancang apabila memilih tahap perlindungan.",
    "travel.cta.title": "Lindungi Perjalanan Anda",
    "travel.cta.text": "Hubungi kakitangan kami untuk mengetahui pilihan insurans perjalanan untuk perjalanan anda.",
    "travel.learnaddons": "Lihat Tambahan & Ekstra",
    
    // Add-Ons Page
    "addons.badge": "Ekstra",
    "addons.title": "Tambahan & Ekstra",
    "addons.description": "Tingkatkan perjalanan Thailand anda dengan perkhidmatan tambahan dan ekstra yang mudah.",
    "addons.popular": "Popular",
    "addons.sim.title": "Kad SIM Thailand",
    "addons.sim.description": "Kekal berhubung dengan kad SIM mudah alih Thai untuk data dan panggilan semasa perjalanan anda.",
    "addons.sim.feature.1": "Pakej data dari 3GB hingga tanpa had",
    "addons.sim.feature.2": "Sah untuk 7-30 hari",
    "addons.sim.feature.3": "Meliputi pembawa utama (AIS, DTAC, TrueMove)",
    "addons.sim.feature.4": "Pengaktifan mudah di sempadan atau lebih awal",
    "addons.roadside.title": "Bantuan Jalan Raya",
    "addons.roadside.description": "Bantuan jalan raya kecemasan 24/7 di seluruh Thailand.",
    "addons.roadside.feature.1": "Perkhidmatan tunda (sehingga 50km)",
    "addons.roadside.feature.2": "Jump-start bateri",
    "addons.roadside.feature.3": "Bantuan tayar pancit",
    "addons.roadside.feature.4": "Penghantaran minyak",
    "addons.roadside.feature.5": "Perkhidmatan terkunci",
    "addons.gps.title": "Navigasi GPS",
    "addons.gps.description": "Sewaan peranti GPS mudah alih dengan peta Thailand yang dipramuat.",
    "addons.gps.feature.1": "Liputan peta Thailand penuh",
    "addons.gps.feature.2": "Navigasi belokan demi belokan",
    "addons.gps.feature.3": "Tempat menarik termasuk",
    "addons.gps.feature.4": "Sokongan pelbagai bahasa",
    "addons.emergency.title": "Kad Talian Kecemasan",
    "addons.emergency.description": "Kad rujukan pantas dengan semua nombor kecemasan dan kenalan bantuan.",
    "addons.emergency.feature.1": "Nombor kecemasan Thai (polis, ambulans, bomba)",
    "addons.emergency.feature.2": "Talian sokongan 24/7 kami",
    "addons.emergency.feature.3": "Nombor hubungan kedutaan",
    "addons.emergency.feature.4": "Arahan tuntutan insurans",
    "addons.whoneeds.title": "Siapa Yang Memerlukan Perkhidmatan Ini?",
    "addons.whoneeds.intro": "Perkhidmatan tambahan disyorkan untuk:",
    "addons.whoneeds.1": "Pelawat kali pertama ke Thailand",
    "addons.whoneeds.2": "Mereka yang membuat perjalanan jalan raya panjang melebihi bandar sempadan",
    "addons.whoneeds.3": "Pelancong yang mahu kekal berhubung dengan keluarga",
    "addons.whoneeds.4": "Pemandu yang mahukan ketenangan fikiran dengan sokongan jalan raya 24/7",
    "addons.misunderstandings": "Salah Faham Biasa",
    "addons.myth.1": "Telefon Malaysia saya akan berfungsi dengan baik di Thailand",
    "addons.fact.1": "Walaupun perayauan berfungsi, kos data mahal. SIM Thai memberikan nilai yang lebih baik.",
    "addons.myth.2": "Saya boleh guna Google Maps secara luar talian sahaja",
    "addons.fact.2": "Peta luar talian tidak menunjukkan trafik atau menyediakan penghalaan semula masa nyata. Pertimbangkan GPS untuk perjalanan panjang.",
    "addons.myth.3": "Bantuan jalan raya hanya untuk kereta lama",
    "addons.fact.3": "Tayar pancit, bateri mati, dan terkunci boleh berlaku kepada mana-mana kenderaan tanpa mengira usia.",
    "addons.availability.title": "Ketersediaan",
    "addons.availability.text": "Perkhidmatan tambahan tertakluk kepada ketersediaan dan mungkin berbeza. Hubungi kakitangan kami untuk tawaran dan harga semasa. Sesetengah perkhidmatan mungkin memerlukan tempahan awal. Semua tambahan boleh diatur bersama permohonan insurans anda.",
    "addons.cta.title": "Berminat dengan Tambahan?",
    "addons.cta.text": "Hubungi kakitangan kami untuk mengetahui tentang ekstra yang tersedia untuk perjalanan anda.",
    "addons.viewdocuments": "Lihat Dokumen Diperlukan",
    
    // Insurance Comparison Section
    "compare.badge": "Bandingkan Perlindungan",
    "compare.title": "Insurans Wajib vs Sukarela",
    "compare.description": "Fahami perbezaan utama antara perlindungan wajib dan sukarela untuk membuat keputusan yang tepat.",
    "compare.feature": "Ciri Perlindungan",
    "compare.compulsory": "Wajib",
    "compare.compulsory.sub": "Por Ror Bor / TPBI",
    "compare.voluntary": "Wajib + Sukarela",
    "compare.voluntary.sub": "Perlindungan Lengkap",
    "compare.recommended": "Disyorkan",
    "compare.feature.legal": "Diperlukan secara sah untuk masuk Thailand",
    "compare.feature.thirdparty": "Kecederaan badan pihak ketiga",
    "compare.feature.property": "Kerosakan harta pihak ketiga",
    "compare.feature.ownvehicle": "Kerosakan kenderaan sendiri",
    "compare.feature.highermedical": "Had perlindungan perubatan lebih tinggi",
    "compare.feature.duitpau": "Perlindungan dari tuntutan \"duit pau\"",
    "compare.feature.legal.liability": "Perlindungan liabiliti undang-undang",
    "compare.note.comprehensive": "Memerlukan insurans komprehensif",
    "compare.compulsory.summary": "Perlindungan asas wajib untuk kecederaan badan sahaja. Diwajibkan undang-undang tetapi perlindungan terhad.",
    "compare.voluntary.summary": "Perlindungan lengkap termasuk kerosakan harta. Sangat disyorkan untuk ketenangan fikiran.",
    
    // Border Guide Page
    "nav.borderguide": "Panduan Sempadan",
    "border.badge": "Panduan Langkah demi Langkah",
    "border.title": "Panduan Merentasi Sempadan Thailand",
    "border.description": "Ketahui apa yang dijangkakan di pusat pemeriksaan sempadan. Ikuti panduan visual ini untuk pengalaman merentasi yang lancar.",
    "border.overview.title": "Apa yang Dijangkakan",
    "border.overview.text": "Merentasi sempadan Malaysia-Thailand dengan kenderaan biasanya mengambil masa 30 minit hingga 2 jam bergantung pada trafik. Proses ini melibatkan imigresen keluar Malaysia, imigresen masuk Thai, kastam kenderaan, dan pengesahan insurans. Bersedia dengan semua dokumen akan mempercepatkan proses.",
    "border.step1.title": "Imigresen Keluar Malaysia",
    "border.step1.description": "Pertama, anda akan melalui imigresen Malaysia di dewan perlepasan. Kemukakan pasport anda untuk cop keluar. Semua penumpang mesti turun dan melalui pusat pemeriksaan.",
    "border.step1.tip1": "Sediakan semua pasport dan mudah diakses",
    "border.step1.tip2": "Tanggalkan topi dan cermin mata hitam untuk pengesahan foto",
    "border.step1.tip3": "Simpan dokumen kenderaan untuk rujukan pantas",
    "border.step2.title": "Pengesahan Insurans",
    "border.step2.description": "Sebelum meneruskan ke imigresen Thai, anda memerlukan insurans kenderaan Thai yang sah. Jika anda mengatur insurans dengan kami terlebih dahulu, sediakan dokumen polisi untuk pemeriksaan.",
    "border.step2.tip1": "Pastikan insurans meliputi keseluruhan tempoh perjalanan",
    "border.step2.tip2": "Simpan salinan fizikal dan digital polisi anda",
    "border.step2.tip3": "Sahkan pendaftaran kenderaan sepadan dengan insurans",
    "border.step3.title": "Pemeriksaan Kastam Kenderaan",
    "border.step3.description": "Kenderaan anda akan menjalani pemeriksaan kastam. Pegawai mungkin memeriksa but dan interior anda. Item larangan termasuk makanan tertentu, senjata, dan bahan terkawal.",
    "border.step3.tip1": "Isytiharkan sebarang item jika tidak pasti tentang peraturan",
    "border.step3.tip2": "Pastikan kenderaan anda bersih dan teratur",
    "border.step3.tip3": "Sediakan pendaftaran kenderaan (Geran) untuk ditunjukkan",
    "border.step4.title": "Imigresen Masuk Thai",
    "border.step4.description": "Kemukakan pasport anda di imigresen Thai untuk cop masuk. Anda mungkin perlu mengisi kad ketibaan/perlepasan. Rakyat Malaysia biasanya mendapat kemasukan bebas visa 30 hari.",
    "border.step4.tip1": "Isi kad ketibaan TM6 jika diperlukan",
    "border.step4.tip2": "Simpan kad perlepasan dengan selamat - anda memerlukannya semasa keluar",
    "border.step4.tip3": "Ketahui alamat yang anda tuju di Thailand",
    "border.step5.title": "Masuk Thailand",
    "border.step5.description": "Setelah diluluskan, anda boleh memandu masuk ke Thailand. Ingat untuk memandu di sebelah kiri (sama seperti Malaysia). Ikuti peraturan lalu lintas tempatan dan had laju.",
    "border.step5.tip1": "Tukar ke zon waktu Thai (sama dengan Malaysia)",
    "border.step5.tip2": "Sediakan Thai Baht untuk tol dan perbelanjaan",
    "border.step5.tip3": "Muat turun peta luar talian untuk destinasi anda",
    "border.tips.label": "Petua",
    "border.essential.title": "Petua Penting untuk Merentasi Sempadan",
    "border.tips.timing.title": "Masa Merentasi Terbaik",
    "border.tips.timing.desc": "Pagi hari bekerja (7-9 PG) biasanya kurang sesak. Elakkan cuti umum dan hujung minggu panjang.",
    "border.tips.photos.title": "Ambil Gambar",
    "border.tips.photos.desc": "Gambar dokumen, polisi insurans, dan jarak kenderaan sebelum merentasi untuk rekod anda.",
    "border.tips.money.title": "Mata Wang & Pembayaran",
    "border.tips.money.desc": "Bawa Thai Baht untuk perbelanjaan. ATM tersedia di sebelah Thai. Kebanyakan tempat terima tunai sahaja.",
    "border.tips.language.title": "Bantuan Bahasa",
    "border.tips.language.desc": "Frasa Thai asas membantu. Pegawai sempadan biasanya bercakap sedikit Inggeris. Aplikasi terjemahan berguna.",
    "border.warning.title": "Peringatan Penting",
    "border.warning.text": "Prosedur sempadan mungkin berbeza dan tertakluk kepada perubahan. Panduan ini adalah untuk rujukan umum sahaja. Sentiasa ikut arahan pegawai imigresen dan kastam. Keperluan mungkin berbeza berdasarkan peraturan semasa, masa hari, atau lokasi pusat pemeriksaan.",
    "border.cta.title": "Bersedia untuk Merentasi Sempadan?",
    "border.cta.text": "Pastikan anda mempunyai semua dokumen yang diperlukan dan insurans yang sah sebelum perjalanan.",
    "border.cta.documents": "Lihat Dokumen Diperlukan",
    
    // Border Locations
    "border.locations.title": "Lokasi Sempadan Rentas",
    "border.location.icqs": "Imigresen, Kastam, Kuarantin & Keselamatan",
    "border.location.bkh.title": "Lokasi Sempadan Bukit Kayu Hitam",
    "border.location.bkh.short": "Bukit Kayu Hitam",
    "border.location.bkh.name": "Kompleks ICQS Bukit Kayu Hitam",
    "border.location.bkh.context": "Sempadan paling sibuk dan popular antara Malaysia dan Thailand. Terletak di Kedah, ia menyediakan akses terus ke Sadao, Thailand dan sesuai untuk pelancong ke Hat Yai dan seterusnya.",
    "border.location.pb.title": "Lokasi Sempadan Padang Besar",
    "border.location.pb.short": "Padang Besar",
    "border.location.pb.name": "Kompleks ICQS Padang Besar",
    "border.location.pb.context": "Sempadan utama yang kerap digunakan oleh pelancong ke Hat Yai, dengan akses terus ke rangkaian kereta api Thailand.",
    "border.location.wk.title": "Lokasi Sempadan Wang Kelian",
    "border.location.wk.short": "Wang Kelian",
    "border.location.wk.name": "Kompleks ICQS Wang Kelian",
    "border.location.wk.context": "Dahulunya popular kerana pasar sempadan. Walaupun kurang aktif hari ini, ia kekal sebagai pilihan rentas yang boleh diakses.",
    "border.location.db.title": "Lokasi Sempadan Durian Burung",
    "border.location.db.short": "Durian Burung",
    "border.location.db.name": "Kompleks ICQS Durian Burung",
    "border.location.db.context": "Sempadan paling baharu dan sunyi. Lokasinya yang terpencil menghasilkan trafik yang lebih rendah, sesuai untuk pelancong yang mencari kurang kesesakan.",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("en");

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
